Repository alicevision/CCTag, pull requests merged in 2019-07, with the labels that each got.

#104 Compatibility with opencv4
  .gitignore
  CMakeLists.txt
  README.md
  appveyor.yml
  cmake/Config.cmake.in
  src/applications/CMakeLists.txt
  src/applications/detection/main.cpp
  src/applications/regression/TestLog.cpp
  src/applications/regression/TestLog.h
  src/applications/simulation/main.cpp
  src/cctag/Bresenham.hpp
  src/cctag/Level.cpp
  src/cctag/filter/thinning.hpp
Labels: build:windows, scope:build

#105 Disable debug code to avoid build issues
  CMakeLists.txt
  src/cctag/cuda/debug_is_on_edge.cu
  src/cctag/cuda/debug_is_on_edge.h
  src/cctag/cuda/frame_06_graddesc.cu
Labels: scope:build

#106 Fix/fewer cuda warnings
  CMakeLists.txt
  cmake/CheckNvccCompilerFlag.cmake
  src/cctag/cuda/geom_matrix.h
Labels: scope:build

#107 Fix/unique mutex use error
  src/cctag/cuda/tag_threads.cu
  src/cctag/cuda/tag_threads.h
Labels: bugfix
