Repository alicevision/CCTag, pull requests merged in 2020-05, with the labels that each got.

#125 CUDA Cub dep has been removed?
  INSTALL.md
  cmake/config.hpp.in
  src/CMakeLists.txt
Labels: scope:doc

#128 adding note re CUDA not yet working on Windows
  INSTALL.md
Labels: scope:doc

#130 [doc] add docs for contribution
  .clang-format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question_help.md
  .github/pull_request_template.md
  .github/workflows/stale.yml
  CHANGES.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  COPYING.md
  README.md
  markersToPrint/generators/3Crowns/ids.txt
  markersToPrint/generators/4Crowns/ids.txt
Labels: scope:doc

#133 [doc] Added badges
  CHANGES.md
  README.md
Labels: scope:doc

#129 [CMake] fixes and improvements
  .travis.yml
  CMakeLists.txt
  Dockerfile
  appveyor.yml
  cmake/Config.cmake.in
  cmake/FindEigen.cmake
  cmake/FindTBB.cmake
  cmake/cctagHelper.cmake
  cmake/version.hpp.in
  src/CMakeLists.txt
  src/applications/CMakeLists.txt
  src/cctag/cmake_install.cmake
Labels: build:windows, linux, scope:build

#131 [docker] split into deps and Actions CI
  .github/workflows/continuous-integration.yml
  Dockerfile
  Dockerfile_deps
  README.md
Labels: docker, scope:ci
